language: python
cache: pip
python:
  - 2.7
  - 3.5
  - 3.6
install:
  - make develop install
script:
  - nosetests -c etc/tests.cfg --with-coverage --cover-package=situation
after_success:
  - coveralls --rcfile=.coveragerc
