language: python
cache: pip
python:
  - 2.7
  - 3.6
install:
  - make develop install
script:
  - make coverage
after_success:
  - coveralls
notifications:
  webhooks:
    urls:
      - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGlhbmRlbm5pc21pbGxlciUzQW1hdHJpeC5vcmcvJTIxWXRJVmRZVlpEQVlNSWl6RU9pJTNBbWF0cml4Lm9yZw"
    on_success: change  # always|never|change
    on_failure: always
    on_start: never
